# Generated by Django 4.2.10 on 2026-02-18 05:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(db_index=True, max_length=8, unique=True)),
                ('hashed_key', models.CharField(max_length=128)),
                ('name', models.CharField(help_text='Friendly name for this key', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prefix', 'is_active'], name='auth_keys_a_prefix_81c5cc_idx')],
            },
        ),
    ]
