# Generated by Django 4.2.10 on 2026-02-18 05:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_keys', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-facing dataset name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('row_count', models.IntegerField(default=0)),
                ('table_name', models.CharField(help_text='Dynamic SQLite table name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='auth_keys.apikey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Original column name from file', max_length=255)),
                ('field_name', models.CharField(help_text='Sanitized Python/Django field name', max_length=255)),
                ('data_type', models.CharField(help_text='Detected type: text, integer, float, boolean, date, datetime', max_length=50)),
                ('field_type', models.CharField(help_text='Django field class name', max_length=50)),
                ('nullable', models.BooleanField(default=True)),
                ('unique', models.BooleanField(default=False)),
                ('max_length', models.IntegerField(blank=True, help_text='For CharField', null=True)),
                ('sample_values', models.JSONField(default=list, help_text='First 5 values for preview')),
                ('position', models.IntegerField(help_text='Column order in original file')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.dataset')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('dataset', 'field_name')},
            },
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['slug'], name='core_datase_slug_997f22_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['status'], name='core_datase_status_1c4df5_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['api_key', 'created_at'], name='core_datase_api_key_44a8c4_idx'),
        ),
    ]
